### ISSUE TITLE
ASC/DESC ....?????

### ISSUE THREAD

**Issue by Nerajno** [learn-co-curriculum/jsdom-task-lister-lite#2]
What does this mean ? The user has limited time to read and grasp concepts, please make the language as clear as possible as for your new users/ learners.

**Comment by maxwellbenton** [comment]
Hi @Nerajno,

Thank you for providing this feedback. We've replaced the reference to ASC/DESC with their full words, ascending and descending.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
